#!/usr/bin/env python3
"""One-off generator for tc_rows_002_010.json — artifact-backed TC rows."""
import json
from pathlib import Path

OUT = Path(__file__).parent / "tc_rows_002_010.json"


def row(spec, D, E, F, G, H):
    return {"spec": spec, "D": D, "E": E, "F": F, "G": G, "H": H}


rows = []

# ========== 002 remove-mailercheck (14) ==========
rows += [
    row(
        "002",
        "mailerCheck 연동 제거",
        "mailercheck 설정 없이 애플리케이션 기동",
        "mailercheck.host 등 연동 전용 설정 없이 local 프로필에서 기동이 실패하지 않음을 확인한다.",
        "1. 배포 구성에서 mailercheck.host·MAILERCHECK_* env를 제거한다.\n2. local 프로필로 애플리케이션을 기동한다.\n3. 기동 로그에서 mailerCheck Feign·Util 의존 오류가 없는지 확인한다.",
        "[요청 예시]\n(설정) mailercheck.host 미설정\n\n[기대 응답 예시]\n애플리케이션 정상 기동\n\n[DB 확인 예시]\n해당 없음(SC-001)",
    ),
    row(
        "002",
        "mailerCheck 연동 제거",
        "POST /mailercheck/single 엔드포인트 404",
        "삭제된 mailerCheck 전용 Internal API가 더 이상 노출되지 않음을 확인한다.",
        "1. Internal API 클라이언트를 준비한다.\n2. POST /v1/api/account/mailercheck/single 을 호출한다.\n3. HTTP 응답 코드를 확인한다.",
        "[요청 예시]\nPOST /v1/api/account/mailercheck/single\nContent-Type: application/json\n\n[기대 응답 예시]\nHTTP 404\n\n[DB 확인 예시]\n해당 없음",
    ),
    row(
        "002",
        "mailerCheck 연동 제거",
        "POST /mailercheck/single/async 엔드포인트 404",
        "비동기 mailerCheck job 제출 API 제거를 확인한다.",
        "1. POST /v1/api/account/mailercheck/single/async 를 호출한다.\n2. HTTP 응답을 확인한다.",
        "[요청 예시]\nPOST /v1/api/account/mailercheck/single/async\n\n[기대 응답 예시]\nHTTP 404",
    ),
    row(
        "002",
        "mailerCheck 연동 제거",
        "GET /mailercheck/single/async/{id} 엔드포인트 404",
        "비동기 mailerCheck 결과 조회 API 제거를 확인한다.",
        "1. GET /v1/api/account/mailercheck/single/async/{job_id} 를 호출한다.\n2. HTTP 응답을 확인한다.",
        "[요청 예시]\nGET /v1/api/account/mailercheck/single/async/{job_id}\n\n[기대 응답 예시]\nHTTP 404",
    ),
    row(
        "002",
        "ID 중복 확인",
        "GET /id 응답에서 mailerCheckStatus 필드 제거",
        "이메일 형식 ID 중복 확인 시 mailerCheckStatus 없이 INTAPI_200 또는 INTAPI_701만 반환함을 확인한다.",
        "1. flowToken·userName·ci 등 필수 파라미터를 준비한다.\n2. GET /v1/api/account/id 를 호출한다.\n3. 응답 JSON 키와 resultcode를 확인한다.",
        "[요청 예시]\nGET /v1/api/account/id?id=user@example.com&flowToken={flow_token}&userName=홍길동&ci={ci}\n\n[기대 응답 예시]\nHTTP 200\nresultcode: INTAPI_200 또는 INTAPI_701\nmailerCheckStatus 키 없음",
    ),
    row(
        "002",
        "ID 중복 확인",
        "GET /id 시 외부 mailerCheck 미호출",
        "이메일 형식 ID 중복 확인 처리 중 외부 메일 실존 검증을 호출하지 않음을 확인한다.",
        "1. mailerCheck env 없이 GET /id 를 호출한다.\n2. MailerCheck Feign 호출이 없는지 확인한다.\n3. UTIL_1004 미발생을 확인한다.",
        "[요청 예시]\nGET /v1/api/account/id?id=test@example.com&flowToken={flow_token}&userName=테스트&ci={ci}\n\n[기대 응답 예시]\nresultcode: INTAPI_200 또는 INTAPI_701 (UTIL_1004 미발생)",
    ),
    row(
        "002",
        "ID 생성·가입",
        "POST /id 가입 시 mailerCheck 단계 없음",
        "가입 시 mailerCheckStatus 필드·UTIL_1006 미발생을 확인한다.",
        "1. POST /v1/api/account/id (addUnfUser) 를 호출한다.\n2. 응답 DTO와 resultcode를 확인한다.",
        "[요청 예시]\nPOST /v1/api/account/id\nContent-Type: application/json\n\n[기대 응답 예시]\nRes_AddUnfUserDto: mailerCheckStatus 필드 없음\nUTIL_1006 미발생",
    ),
    row(
        "002",
        "회원정보 변경",
        "POST /api/account 대표이메일 변경 시 mailerCheck 미호출",
        "updUnfUser에서 UTIL_1004/1006 미발생을 확인한다.",
        "1. POST /v1/api/account (updUnfUser) 로 email 변경을 요청한다.\n2. resultcode를 확인한다.",
        "[요청 예시]\nPOST /v1/api/account\nemail: new@example.com\n\n[기대 응답 예시]\nresultcode: 기존 INTAPI_* (UTIL_1004/1006 미발생)",
    ),
    row(
        "002",
        "mailerCheck 연동 제거",
        "UTIL_1003~1008 런타임 미반환",
        "연동 전용 오류 코드가 API 응답에서 더 이상 반환되지 않음을 확인한다.",
        "1. 계정 API 시나리오를 수행한다.\n2. resultcode 1003~1008 미발생을 확인한다.",
        "[기대 응답 예시]\nresultcode: UTIL_1003~1008 미발생\nResCode/ResMsg: 주석(미사용)만 유지",
    ),
    row(
        "002",
        "mailerCheck 연동 제거",
        "MailerCheckException 응답 형식 미노출",
        "mailer_check_status 포함 예외 응답이 제거됨을 확인한다.",
        "1. 계정 API 응답 body를 확인한다.",
        "[기대 응답 예시]\n{ resultcode, message } 만 (mailer_check_status 없음)",
    ),
    row(
        "002",
        "mailerCheck 연동 제거",
        "소스·설정 mailerCheck 잔재 grep 검증",
        "NC1~4 제거 완료를 독립 판정할 수 있음을 확인한다.",
        "1. src/main·k8s에서 MailerCheck|mailercheck grep한다.\n2. UTIL_100[3-8] 활성 참조 0건을 확인한다.",
        "[기대 응답 예시]\nsrc/main 활성 mailercheck 0건\nUTIL_1003~1008: ResCode/ResMsg 주석만",
    ),
    row(
        "002",
        "mailerCheck 연동 제거",
        "이메일 형식 검증 유지",
        "외부 실존 검증과 무관한 형식 오류 검증이 유지됨을 확인한다.",
        "1. 잘못된 이메일 형식으로 GET /id 를 호출한다.\n2. UTIL_1004 미발생을 확인한다.",
        "[요청 예시]\nGET /v1/api/account/id?id=not-an-email&flowToken={flow_token}&...\n\n[기대 응답 예시]\n기존 validation 거절 (UTIL_1004 미발생)",
    ),
    row(
        "002",
        "mailerCheck 연동 제거",
        "Redis mailerCheck 캐시 신규 적재 중단",
        "Util 삭제로 mailerCheck Redis 신규 쓰기가 중단됨을 확인한다.",
        "1. ID·가입 API 호출 후 Redis를 확인한다.",
        "[DB 확인 예시]\nRedis: MailerCheck status 문자열 신규 적재 없음",
    ),
    row(
        "002",
        "mailerCheck 연동 제거",
        "SC-003 NC 4항목 제거 완료 판정",
        "Util·서비스·Feign·연동 전용 오류 표현 제거 완료를 확인한다.",
        "1. NC1~4 각 항목을 독립적으로 예/아니오 판정한다.",
        "[기대 응답 예시]\nNC 1~4 제거 완료: 예",
    ),
]

# ========== 006 sns-disconnect-receive (25) ==========
rows += [
    row(
        "006",
        "SNS 연동 해제",
        "네이버 유효 알림 수신 시 tbl_sns_info 삭제",
        "HMAC 검증 성공 시 sns_type=3 행이 삭제되고 HTTP 204로 응답함을 확인한다.",
        "1. tbl_sns_info에 sns_type=3 매칭 행을 준비한다.\n2. POST /v1/account/sns/naver/disconnect-receive 를 form으로 호출한다.\n3. HTTP 204와 DB 삭제를 확인한다.\n4. GET /v1/api/account/snsinfo 로 beforeConn=0을 확인한다.",
        "[요청 예시]\nPOST /v1/account/sns/naver/disconnect-receive\nContent-Type: application/x-www-form-urlencoded\nclientId={naver_client_id}&encryptUniqueId={encrypted_sns_id}&timestamp={epoch_ms}&signature={hmac_signature}\n\n[기대 응답 예시]\nHTTP 204\n\n[DB 확인 예시]\ntbl_sns_info: sns_type=3, sns_id={복호화값} — (시험 후) 행 삭제",
    ),
    row(
        "006",
        "SNS 연동 해제",
        "네이버 HMAC 불일치 시 DB 미변경",
        "signature 불일치 시 tbl_sns_info 변경 없이 HTTP 401을 반환함을 확인한다.",
        "1. 위조 signature로 네이버 콜백을 호출한다.\n2. HTTP 401과 DB 무변경을 확인한다.",
        "[요청 예시]\nPOST /v1/account/sns/naver/disconnect-receive\nsignature={invalid_hmac}\n\n[기대 응답 예시]\nHTTP 401\n\n[DB 확인 예시]\ntbl_sns_info: 변경 없음",
    ),
    row(
        "006",
        "SNS 연동 해제",
        "네이버 필수 필드 누락 시 HTTP 400",
        "clientId·encryptUniqueId·timestamp·signature 중 누락·빈 값 시 HTTP 400을 반환함을 확인한다.",
        "1. 필수 필드 하나를 누락한 form 요청을 보낸다.\n2. HTTP 400을 확인한다.",
        "[요청 예시]\nPOST /v1/account/sns/naver/disconnect-receive\nclientId={naver_client_id}\n(encryptUniqueId 누락)\n\n[기대 응답 예시]\nHTTP 400",
    ),
    row(
        "006",
        "SNS 연동 해제",
        "네이버 clientId 불일치 시 HTTP 401",
        "설정과 다른 clientId 시 HTTP 401·DB 미변경을 확인한다.",
        "1. 잘못된 clientId로 요청한다.\n2. HTTP 401을 확인한다.",
        "[요청 예시]\nclientId={wrong_client_id}&...\n\n[기대 응답 예시]\nHTTP 401",
    ),
    row(
        "006",
        "SNS 연동 해제",
        "네이버 설정·DB 장애 시 HTTP 500",
        "필수 설정 없음 또는 DB 연결 실패 시 HTTP 500을 반환함을 확인한다.",
        "1. 설정 미구성 또는 DB 장애 환경에서 콜백을 호출한다.\n2. HTTP 500을 확인한다.",
        "[기대 응답 예시]\nHTTP 500",
    ),
    row(
        "006",
        "SNS 연동 해제",
        "네이버 매칭 행 없음 no-op HTTP 204",
        "검증 성공·매칭 행 없을 때 삭제 없이 HTTP 204를 반환함을 확인한다.",
        "1. DB에 매칭 없는 encryptUniqueId로 요청한다.\n2. HTTP 204·DB 무변경을 확인한다.",
        "[기대 응답 예시]\nHTTP 204 (no-op)",
    ),
    row(
        "006",
        "SNS 연동 해제",
        "카카오 유효 웹훅 수신 시 행 삭제",
        "app_id 일치·user_id 매칭 시 sns_type=4 행 삭제 후 HTTP 200을 반환함을 확인한다.",
        "1. tbl_sns_info sns_type=4 행을 준비한다.\n2. GET /v1/account/sns/kakao/disconnect-receive 를 호출한다.\n3. HTTP 200·행 삭제를 확인한다.",
        "[요청 예시]\nGET /v1/account/sns/kakao/disconnect-receive?user_id={kakao_user_id}&app_id={kakao_app_id}&referrer_type={referrer}\n\n[기대 응답 예시]\nHTTP 200\n\n[DB 확인 예시]\ntbl_sns_info: sns_type=4 — 행 삭제",
    ),
    row(
        "006",
        "SNS 연동 해제",
        "카카오 app_id 불일치 시 DB 미변경 HTTP 200",
        "app_id 불일치 시에도 HTTP 200·tbl_sns_info 무변경을 확인한다.",
        "1. 잘못된 app_id로 GET 웹훅을 호출한다.\n2. HTTP 200·DB 무변경을 확인한다.",
        "[요청 예시]\nGET ...?user_id={id}&app_id={wrong_app_id}\n\n[기대 응답 예시]\nHTTP 200\n\n[DB 확인 예시]\ntbl_sns_info: 변경 없음",
    ),
    row(
        "006",
        "SNS 연동 해제",
        "카카오 내부 오류 시에도 HTTP 200",
        "이용자 없음·내부 오류 포함 처리 후 HTTP 200(3초 이내)을 확인한다.",
        "1. 오류 유발 웹훅을 호출한다.\n2. HTTP 200·응답 시간을 확인한다.",
        "[기대 응답 예시]\nHTTP 200 (3초 이내)",
    ),
    row(
        "006",
        "SNS 연동 해제",
        "애플 consent-revoked 이벤트 행 삭제",
        "payload 검증 성공·events.type=consent-revoked 시 sns_type=5 행 삭제·HTTP 200을 확인한다.",
        "1. 유효 Apple JWT payload를 준비한다.\n2. POST /v1/account/sns/apple/disconnect-receive 를 호출한다.\n3. HTTP 200·행 삭제를 확인한다.",
        "[요청 예시]\nPOST /v1/account/sns/apple/disconnect-receive\nContent-Type: application/json\n{\"payload\": \"{signed_jwt}\"}\n\n[기대 응답 예시]\nHTTP 200\n\n[DB 확인 예시]\ntbl_sns_info: sns_type=5, sns_id=events.sub — 행 삭제",
    ),
    row(
        "006",
        "SNS 연동 해제",
        "애플 account-delete 이벤트 행 삭제",
        "events.type=account-delete 시 동일 삭제·HTTP 200을 확인한다.",
        "1. account-delete 이벤트 JWT로 POST한다.\n2. HTTP 200·행 삭제를 확인한다.",
        "[기대 응답 예시]\nHTTP 200",
    ),
    row(
        "006",
        "SNS 연동 해제",
        "애플 payload 누락 시 HTTP 400",
        "body에 payload 없음 시 HTTP 400을 확인한다.",
        "1. payload 없는 JSON body로 POST한다.\n2. HTTP 400을 확인한다.",
        "[기대 응답 예시]\nHTTP 400",
    ),
    row(
        "006",
        "SNS 연동 해제",
        "애플 iss·aud 불일치 시 HTTP 401",
        "iss≠https://appleid.apple.com 또는 aud≠apple.clientId 시 HTTP 401·DB 미변경을 확인한다.",
        "1. aud 불일치 JWT로 POST한다.\n2. HTTP 401을 확인한다.",
        "[기대 응답 예시]\nHTTP 401\n\n[DB 확인 예시]\ntbl_sns_info: 변경 없음",
    ),
    row(
        "006",
        "SNS 연동 해제",
        "애플 설정·DB 장애 시 HTTP 500",
        "필수 설정 없음·DB 실패 시 HTTP 500을 확인한다.",
        "1. 장애 환경에서 Apple Notifications를 호출한다.",
        "[기대 응답 예시]\nHTTP 500",
    ),
    row(
        "006",
        "SNS 연동 해제",
        "12.2 목록 삭제 후 beforeConn=0",
        "인바운드 삭제 후 12.2에서 해당 sns_type이 beforeConn=0·빈 snsId만 표시됨을 확인한다.",
        "1. 인바운드 삭제 후 GET /v1/api/account/snsinfo 를 호출한다.",
        "[요청 예시]\nGET /v1/api/account/snsinfo\nAuthorization: Bearer {ACCESS_TOKEN}\n\n[기대 응답 예시]\n해당 sns_type: beforeConn=0, snsId=\"\"",
    ),
    row(
        "006",
        "SNS 연동 해제",
        "동일 SNS 재연동 가능",
        "행 삭제 후 12.3 active_yn=Y로 재연동이 가능함을 확인한다.",
        "1. 삭제 완료 이용자로 POST /v1/api/account/snsinfo (active_yn=Y)를 호출한다.\n2. tbl_sns_info 신규 행·12.2 연결 표시를 확인한다.",
        "[DB 확인 예시]\ntbl_sns_info: 동일 sns_id로 insert/update 가능",
    ),
    row(
        "006",
        "회원 탈퇴",
        "6.13 통합 회원 탈퇴 시 SNS 선행 삭제",
        "tbl_user 삭제 전 id_key의 모든 tbl_sns_info 행이 삭제됨을 확인한다.",
        "1. 여러 sns_type 행이 있는 이용자로 POST /v1/api/account/withdraw 를 호출한다.\n2. 탈퇴 전후 tbl_sns_info 건수를 확인한다.",
        "[DB 확인 예시]\ntbl_sns_info: id_key={id_key} — (탈퇴 후) 0건\ntbl_user: 해당 id_key 삭제",
    ),
    row(
        "006",
        "회원 탈퇴",
        "11.3 관리자 탈퇴 시 SNS 선행 삭제",
        "관리자 탈퇴 시에도 deleteAllSnsInfoByIdKey 후 delUnfUser 순서를 확인한다.",
        "1. POST /v1/api/account/admin/withdraw 를 호출한다.\n2. tbl_sns_info 0건을 확인한다.",
        "[DB 확인 예시]\ntbl_sns_info: id_key 기준 0건 (sns_type 6 포함)",
    ),
    row(
        "006",
        "SNS 연동 설정",
        "12.3 active_yn=N revoke 성공 후 행 삭제",
        "SNS 제공자 연동 해제 API 성공 시 행 삭제·active_yn N 갱신 없음을 확인한다.",
        "1. 연동된 네이버 행을 준비한다.\n2. POST /v1/api/account/snsinfo (active_yn=N)를 호출한다.\n3. revoke 성공·행 삭제·12.2 beforeConn=0을 확인한다.",
        "[요청 예시]\nPOST /v1/api/account/snsinfo\nAuthorization: Bearer {ACCESS_TOKEN}\n{\"sns_type\":3,\"active_yn\":\"N\",\"sns_token\":\"{access_token}\",\"client_id\":\"{client_id}\"}\n\n[기대 응답 예시]\nresultcode: 200\n\n[DB 확인 예시]\ntbl_sns_info: 해당 행 삭제",
    ),
    row(
        "006",
        "SNS 연동 설정",
        "12.3 active_yn=N revoke 실패 시 720~722",
        "SNS 제공자 연동 해제 실패 시 tbl_sns_info 무변경·720/721/722를 확인한다.",
        "1. revoke 실패 mock으로 12.3 N 요청을 보낸다.\n2. resultcode와 DB를 확인한다.",
        "[기대 응답 예시]\nHTTP 200\nresultcode: 720(네이버)/721(카카오)/722(애플)\n\n[DB 확인 예시]\ntbl_sns_info: 변경 없음",
    ),
    row(
        "006",
        "SNS 연동 설정",
        "12.3 revoke 성공·DELETE 실패 시 HTTP 500",
        "FR-074: revoke 성공·DB DELETE 실패 시 HTTP 500·행 유지를 확인한다.",
        "1. revoke 성공·DELETE 실패 환경에서 12.3 N을 호출한다.",
        "[기대 응답 예시]\nHTTP 500\n\n[DB 확인 예시]\ntbl_sns_info: 행 유지",
    ),
    row(
        "006",
        "SNS 연동 설정",
        "6.20 active_yn=N 요청 HTTP 400",
        "6.20은 연동 Y 전용이며 active_yn=N은 거부됨을 확인한다.",
        "1. POST /v1/api/account/id/snsinfo 에 active_yn=N을 보낸다.\n2. validation/400을 확인한다.",
        "[요청 예시]\nPOST /v1/api/account/id/snsinfo\n{\"active_yn\":\"N\",...}\n\n[기대 응답 예시]\nHTTP 400",
    ),
    row(
        "006",
        "SNS 연동 해제",
        "위조 알림 수신 시 tbl_sns_info 미변경",
        "검증 실패 알림 100% DB 무변경을 확인한다(SC-002).",
        "1. 제공자별 위조 알림을 전송한다.\n2. tbl_sns_info 변경 없음을 확인한다.",
        "[DB 확인 예시]\ntbl_sns_info: 변경 없음",
    ),
    row(
        "006",
        "SNS 연동 해제",
        "중복 알림 멱등 처리",
        "이미 삭제된 행에 재알림 시 no-op·제공자별 응답 정책 유지를 확인한다.",
        "1. 삭제 후 동일 알림을 재전송한다.\n2. 네이버 204·카카오 200·애플 200을 확인한다.",
        "[기대 응답 예시]\n네이버 HTTP 204 / 카카오·애플 HTTP 200 (no-op)",
    ),
    row(
        "006",
        "SNS 연동 설정",
        "12.3 애플 N 시 refresh_token 필드 사용",
        "sns_type=5·active_yn=N 시 refresh_token(apple_refresh_token→refresh_token)으로 revoke함을 확인한다.",
        "1. 애플 연동 행으로 12.3 N 요청(refresh_token 포함)을 보낸다.\n2. revoke·DELETE를 확인한다.",
        "[요청 예시]\nPOST /v1/api/account/snsinfo\n{\"sns_type\":5,\"active_yn\":\"N\",\"refresh_token\":\"{apple_refresh_token}\",...}",
    ),
]

# ========== 007 oversea-login-block (25) ==========
rows += [
    row(
        "007",
        "해외 로그인 차단",
        "12.1 조회 login_block_status=1",
        "DB overseas_login_block=1일 때 12.1 응답 login_block_status=1을 확인한다.",
        "1. tbl_user.overseas_login_block=1 이용자로 로그인한다.\n2. GET /v1/api/account/userloginmanage/info 를 호출한다.",
        "[요청 예시]\nGET /v1/api/account/userloginmanage/info\nAuthorization: Bearer {ACCESS_TOKEN}\n\n[기대 응답 예시]\nresultcode: 200\nlogin_block_status: 1\n\n[DB 확인 예시]\ntbl_user.overseas_login_block: 1",
    ),
    row(
        "007",
        "해외 로그인 차단",
        "12.1 조회 login_block_status=0 (DB 0/NULL)",
        "DB 0 또는 NULL일 때 API login_block_status=0을 확인한다.",
        "1. overseas_login_block=0 또는 NULL 이용자로 12.1을 호출한다.",
        "[기대 응답 예시]\nlogin_block_status: 0",
    ),
    row(
        "007",
        "해외 로그인 차단",
        "12.1 AccessToken 무효 시 인증 실패",
        "AccessToken 없음·무효 시 기존 12.1 인증 실패 정책을 확인한다.",
        "1. Authorization 헤더 없이 12.1을 호출한다.",
        "[기대 응답 예시]\nHTTP 401 등 (기존 @AuthChk 정책)",
    ),
    row(
        "007",
        "해외 로그인 차단",
        "12.4 login_block_status=1 설정",
        "12.4로 차단 설정 시 DB·12.1이 1로 일치함을 확인한다.",
        "1. POST /v1/api/account/overseas-login-block 에 login_block_status=1을 보낸다.\n2. 12.1·DB를 확인한다.",
        "[요청 예시]\nPOST /v1/api/account/overseas-login-block\nAuthorization: Bearer {ACCESS_TOKEN}\n{\"login_block_status\": 1}\n\n[기대 응답 예시]\nresultcode: 200\n\n[DB 확인 예시]\ntbl_user.overseas_login_block: 1",
    ),
    row(
        "007",
        "해외 로그인 차단",
        "12.4 login_block_status=0 설정",
        "12.4로 해제 시 DB·12.1이 0으로 일치함을 확인한다.",
        "1. login_block_status=0으로 12.4를 호출한다.",
        "[요청 예시]\n{\"login_block_status\": 0}\n\n[기대 응답 예시]\nresultcode: 200\nlogin_block_status(12.1): 0",
    ),
    row(
        "007",
        "해외 로그인 차단",
        "12.4 멱등 재설정",
        "이미 1인 상태에서 다시 1 설정 시 성공(멱등)을 확인한다.",
        "1. login_block_status=1을 연속 2회 호출한다.",
        "[기대 응답 예시]\nresultcode: 200 (양쪽)",
    ),
    row(
        "007",
        "해외 로그인 차단",
        "12.4 AccessToken 없음 거절",
        "12.4는 AccessToken 필수임을 확인한다.",
        "1. Authorization 없이 12.4를 호출한다.",
        "[기대 응답 예시]\n인증 실패",
    ),
    row(
        "007",
        "해외 로그인 차단",
        "12.4 login_block_status 유효값 외 거절",
        "login_block_status가 0·1이 아니면 검증 실패를 확인한다.",
        "1. login_block_status=2로 12.4를 호출한다.",
        "[기대 응답 예시]\nHTTP 400 또는 validation 실패",
    ),
    row(
        "007",
        "해외 로그인 차단",
        "12.4 회원 정보 없음 703",
        "토큰 유효·회원 없음 시 resultcode 703을 확인한다.",
        "1. 존재하지 않는 회원 토큰으로 12.4를 호출한다.",
        "[기대 응답 예시]\nHTTP 200\nresultcode: 703",
    ),
    row(
        "007",
        "해외 로그인 차단",
        "11.5 관리자 차단 설정 login_block_status=1",
        "11.5로 특정 user_id 차단 설정 시 DB=1을 확인한다.",
        "1. POST /v1/api/account/admin/overseas-login-block 를 호출한다.",
        "[요청 예시]\nPOST /v1/api/account/admin/overseas-login-block\n{\"id\": \"{user_id}\", \"login_block_status\": 1}\n\n[기대 응답 예시]\nresultcode: 200\n\n[DB 확인 예시]\ntbl_user.overseas_login_block: 1",
    ),
    row(
        "007",
        "해외 로그인 차단",
        "11.5 관리자 해제 login_block_status=0",
        "관리자가 OTP 없이 0으로 해제함을 확인한다.",
        "1. login_block_status=0으로 11.5를 호출한다.",
        "[기대 응답 예시]\nresultcode: 200\nDB: 0",
    ),
    row(
        "007",
        "해외 로그인 차단",
        "11.5 존재하지 않는 id 700",
        "없는 user_id 시 resultcode 700을 확인한다.",
        "1. 존재하지 않는 id로 11.5를 호출한다.",
        "[기대 응답 예시]\nHTTP 200\nresultcode: 700\nmessage: ID가 존재하지 않습니다.",
    ),
    row(
        "007",
        "해외 로그인 차단 OTP",
        "6.25 정상 OTP 발송·이력",
        "차단 중(overseas_login_block=1) 이용자 6.25 성공 시 Redis·Argos·tbl_argos_alarm_history를 확인한다.",
        "1. block=1 이용자로 POST …/otp/alarm 을 호출한다.\n2. Redis OTP·이력을 확인한다.",
        "[요청 예시]\nPOST /v1/api/account/overseas-login-block/otp/alarm\n{\"id\": \"{user_id}\"}\n\n[기대 응답 예시]\nresultcode: 200\n\n[DB 확인 예시]\ntbl_argos_alarm_history: send_status=1, template_code=DCB03, send_from=2\nRedis: 6자리 OTP, fail_count=0, TTL 5분",
    ),
    row(
        "007",
        "해외 로그인 차단 OTP",
        "6.25 5분 내 재발급 OTP·fail_count 리셋",
        "동일 id 재요청 시 OTP·fail_count=0·TTL 갱신·Argos 재호출을 확인한다.",
        "1. 6.25 직후 동일 id로 6.25를 재호출한다.",
        "[기대 응답 예시]\nresultcode: 200\nRedis: 새 OTP, fail_count=0",
    ),
    row(
        "007",
        "해외 로그인 차단 OTP",
        "6.25 차단 미설정 742",
        "overseas_login_block=0/NULL 시 742·Argos·Redis 미호출을 확인한다.",
        "1. block=0 이용자로 6.25를 호출한다.",
        "[기대 응답 예시]\nHTTP 200\nresultcode: 742",
    ),
    row(
        "007",
        "해외 로그인 차단 OTP",
        "6.25 mobile_no 없음 743",
        "mobile_no NULL·빈 값 시 743·Argos 미호출을 확인한다.",
        "1. mobile_no 없는 block=1 이용자로 6.25를 호출한다.",
        "[기대 응답 예시]\nresultcode: 743",
    ),
    row(
        "007",
        "해외 로그인 차단 OTP",
        "6.25 Argos 실패 829",
        "Argos 발송 실패 시 829·성공 이력 없음을 확인한다.",
        "1. Argos 실패 mock으로 6.25를 호출한다.",
        "[기대 응답 예시]\nresultcode: 829\n\n[DB 확인 예시]\ntbl_argos_alarm_history: 성공 이력 없음",
    ),
    row(
        "007",
        "해외 로그인 차단 OTP",
        "6.25 존재하지 않는 id 700",
        "없는 id 시 700을 확인한다.",
        "1. 없는 id로 6.25를 호출한다.",
        "[기대 응답 예시]\nresultcode: 700",
    ),
    row(
        "007",
        "해외 로그인 차단 OTP",
        "6.25 Argos 성공·이력 INSERT 실패 829",
        "이력 INSERT 실패 시 829를 확인한다.",
        "1. Argos 성공·INSERT 실패 환경에서 6.25를 호출한다.",
        "[기대 응답 예시]\nresultcode: 829",
    ),
    row(
        "007",
        "해외 로그인 차단 OTP",
        "6.26 OTP 일치 성공·DB 해제",
        "올바른 otp 시 200·OTP 인증 완료·overseas_login_block=0을 확인한다.",
        "1. 6.25 후 POST …/otp/check 를 호출한다.",
        "[요청 예시]\nPOST /v1/api/account/overseas-login-block/otp/check\n{\"id\": \"{user_id}\", \"otp\": \"123456\"}\n\n[기대 응답 예시]\nresultcode: 200\nmessage: OTP 인증 완료\n\n[DB 확인 예시]\ntbl_user.overseas_login_block: 0\nRedis: 키 삭제",
    ),
    row(
        "007",
        "해외 로그인 차단 OTP",
        "6.26 OTP 불일치 737 + fail_count",
        "누적 실패 1~4회 시 737·fail_count를 확인한다.",
        "1. 잘못된 otp로 6.26을 호출한다.",
        "[기대 응답 예시]\nHTTP 200\nresultcode: 737\nfail_count: {누적횟수}",
    ),
    row(
        "007",
        "해외 로그인 차단 OTP",
        "6.26 OTP 5회 초과 738",
        "누적 ≥5 시 738·fail_count를 확인한다.",
        "1. 5회 연속 오입력 후 6.26을 호출한다.",
        "[기대 응답 예시]\nresultcode: 738\nfail_count: ≥5",
    ),
    row(
        "007",
        "해외 로그인 차단 OTP",
        "6.26 Redis 만료 739",
        "OTP 임시 데이터 없음 시 739를 확인한다.",
        "1. TTL 만료 후 6.26을 호출한다.",
        "[기대 응답 예시]\nresultcode: 739\nmessage: 인증번호 입력시간 만료",
    ),
    row(
        "007",
        "해외 로그인 차단 OTP",
        "6.26 존재하지 않는 id 700",
        "6.26에서 없는 id 시 700을 확인한다.",
        "1. 없는 id로 6.26을 호출한다.",
        "[기대 응답 예시]\nresultcode: 700",
    ),
    row(
        "007",
        "해외 로그인 차단",
        "smoke-phase7 12.4·6.25·6.26·11.5 통합",
        "plan §검증·smoke-phase7 시나리오 1~9 대응 통합 확인을 수행한다.",
        "1. smoke-phase7.md 체크리스트 1~9를 순서대로 수행한다.",
        "[기대 응답 예시]\n12.1·12.4·6.25·6.26·11.5 계약 일치",
    ),
]

# ========== 008 google-login-signup (22) ==========
rows += [
    row(
        "008",
        "구글 SNS 연동",
        "POST /sns/google/profile 정상 프로필 조회",
        "유효 id_token·clientId로 프로필 payload 부분 집합을 반환함을 확인한다.",
        "1. AccessToken으로 POST /v1/api/account/sns/google/profile 를 호출한다.\n2. resultcode 200·data 필드를 확인한다.",
        "[요청 예시]\nPOST /v1/api/account/sns/google/profile\nAuthorization: Bearer {ACCESS_TOKEN}\n{\"clientId\": \"{google_client_id}\", \"idToken\": \"{valid_id_token}\"}\n\n[기대 응답 예시]\nresultcode: 200\ndata: sub, email, emailVerified, name, picture, iss, aud, exp",
    ),
    row(
        "008",
        "구글 SNS 연동",
        "구글 프로필 API id_token 검증 실패 744",
        "id_token 검증 실패 시 744를 확인한다.",
        "1. 무효 id_token으로 프로필 API를 호출한다.",
        "[기대 응답 예시]\nresultcode: 744",
    ),
    row(
        "008",
        "구글 SNS 연동",
        "구글 프로필 API clientId 오류 750/803",
        "clientId validation·설정 오류 시 750 또는 803을 확인한다.",
        "1. 잘못된 clientId로 프로필 API를 호출한다.",
        "[기대 응답 예시]\nresultcode: 750 또는 803",
    ),
    row(
        "008",
        "SNS 연동 설정",
        "12.3 구글 연결(Y) tbl_sns_info 저장",
        "sns_type=6·active_yn=Y·id_token으로 연결 행 저장·active_yn=Y를 확인한다.",
        "1. POST /v1/api/account/snsinfo (sns_type=6, active_yn=Y)를 호출한다.\n2. tbl_sns_info·12.2를 확인한다.",
        "[요청 예시]\nPOST /v1/api/account/snsinfo\n{\"sns_type\":6,\"active_yn\":\"Y\",\"sns_token\":\"{id_token}\",\"client_id\":\"{client_id}\"}\n\n[DB 확인 예시]\ntbl_sns_info: sns_type=6, active_yn=Y, sns_account_id·sns_connect_time 저장",
    ),
    row(
        "008",
        "SNS 연동 설정",
        "12.3 구글 해제(N) revoke 후 행 삭제",
        "refresh_token으로 revoke 성공 시 sns_type=6 행 삭제를 확인한다.",
        "1. 연결된 구글 행으로 12.3 N(sns_token=refresh_token)을 호출한다.",
        "[요청 예시]\n{\"sns_type\":6,\"active_yn\":\"N\",\"sns_token\":\"{refresh_token}\",...}\n\n[기대 응답 예시]\nresultcode: 200\n\n[DB 확인 예시]\ntbl_sns_info: sns_type=6 행 삭제",
    ),
    row(
        "008",
        "SNS 연동 설정",
        "12.3 구글 해제 revoke 실패 745",
        "revoke 실패 시 745·행 유지를 확인한다.",
        "1. revoke 실패 mock으로 12.3 N을 호출한다.",
        "[기대 응답 예시]\nresultcode: 745\n\n[DB 확인 예시]\ntbl_sns_info: 행 유지",
    ),
    row(
        "008",
        "SNS 연동 설정",
        "6.20 구글 연결(Y) CI 정합 후 저장",
        "6.20에서 sns_type=6·active_yn=Y·id_token·ci로 저장함을 확인한다.",
        "1. POST /v1/api/account/id/snsinfo 를 호출한다.",
        "[요청 예시]\nPOST /v1/api/account/id/snsinfo\n{\"ci\":\"{ci}\",\"sns_type\":6,\"active_yn\":\"Y\",\"sns_token\":\"{id_token}\",\"client_id\":\"{client_id}\"}",
    ),
    row(
        "008",
        "SNS 연동 설정",
        "6.20 active_yn=N HTTP 400",
        "6.20은 연동 Y 전용이며 N은 거부됨을 확인한다.",
        "1. 6.20에 active_yn=N을 보낸다.",
        "[기대 응답 예시]\nHTTP 400 (validation)",
    ),
    row(
        "008",
        "SNS 연동 목록",
        "12.2 구글 연결됨 표시",
        "구글 연결 이용자 12.2에서 sns_type=6 연결 상태를 확인한다.",
        "1. GET /v1/api/account/snsinfo 를 호출한다.",
        "[기대 응답 예시]\nsns_type=6: beforeConn=1, activeYn=Y",
    ),
    row(
        "008",
        "SNS 연동 목록",
        "12.2 구글 미연결 표시",
        "해제 후 sns_type=6 미연결·식별 정보 미노출을 확인한다.",
        "1. 해제 이용자로 12.2를 호출한다.",
        "[기대 응답 예시]\nsns_type=6: beforeConn=0, snsId=\"\"\n(sns_account_id·연동 일시 미노출)",
    ),
    row(
        "008",
        "SNS 연동 목록",
        "12.2 응답에 sns_account_id 미포함",
        "12.2·프로필 API 응답에 sns_account_id·연동 일시가 없음을 확인한다.",
        "1. 12.2·프로필 API 응답 필드를 확인한다.",
        "[기대 응답 예시]\n12.2: beforeConn, activeYn, snsId만 (email/sns_account_id 없음)",
    ),
    row(
        "008",
        "ActionLog",
        "12.3 구글 연결·해제 sns_type=6 기록",
        "@StatLog 경로로 tbl_user_action_log에 sns_type=6·log_type=407 기록을 확인한다.",
        "1. 12.3 구글 Y/N 처리 후 tbl_user_action_log를 조회한다.",
        "[DB 확인 예시]\ntbl_user_action_log: sns_type=6, log_type=407, proc_result",
    ),
    row(
        "008",
        "ActionLog",
        "6.20 구글 연결(Y) ActionLog 기록",
        "6.20 구글 Y 처리 시 ActionLog sns_type=6을 확인한다.",
        "1. 6.20 구글 Y 후 ActionLog를 조회한다.",
        "[DB 확인 예시]\ntbl_user_action_log: sns_type=6",
    ),
    row(
        "008",
        "ActionLog",
        "sns_type≠6 연결 설정 ActionLog 미생성 유지",
        "네이버·카카오 12.3은 ActionLog 미생성 회귀 없음을 확인한다.",
        "1. sns_type=3 연결 후 ActionLog 건수를 확인한다.",
        "[DB 확인 예시]\ntbl_user_action_log: 구글 외 sns_type 미추가(회귀 없음)",
    ),
    row(
        "008",
        "ActionLog",
        "기존 @StatLog API 회귀 없음",
        "회원가입·탈퇴 등 기존 ActionLog가 변경·누락되지 않음을 확인한다.",
        "1. 기존 @StatLog API 호출 후 로그를 확인한다.",
        "[DB 확인 예시]\ntbl_user_action_log: 기존 필드·의미 유지",
    ),
    row(
        "008",
        "SNS 연동 설정",
        "12.3 미지원 sns_type 717",
        "sns_type 비 3~6 시 717을 확인한다.",
        "1. 지원 외 sns_type으로 12.3을 호출한다.",
        "[기대 응답 예시]\nresultcode: 717",
    ),
    row(
        "008",
        "SNS 연동 설정",
        "12.3 구글 id_token 검증 실패 744",
        "연결 Y 시 id_token 검증 실패 744·저장 없음을 확인한다.",
        "1. 무효 id_token으로 12.3 Y를 호출한다.",
        "[기대 응답 예시]\nresultcode: 744\n\n[DB 확인 예시]\ntbl_sns_info: 저장 없음",
    ),
    row(
        "008",
        "SNS 연동 설정",
        "12.3 구글 insert 실패 724/729",
        "중복·insert 실패 시 724/729를 확인한다.",
        "1. 중복 sns_id로 12.3 Y를 호출한다.",
        "[기대 응답 예시]\nresultcode: 724 또는 729",
    ),
    row(
        "008",
        "SNS 연동 설정",
        "구글 Outbound revoke Feign",
        "해제 N 시 GoogleOAuthClient POST oauth2.googleapis.com/revoke 호출을 확인한다.",
        "1. 12.3 N 호출 시 Feign revoke 요청을 확인한다.",
        "[요청 예시]\nPOST https://oauth2.googleapis.com/revoke\ntoken={refresh_token}",
    ),
    row(
        "008",
        "구글 SNS 연동",
        "검증 실패 시 무단 저장·삭제 없음",
        "토큰 오류 시 003 NC 오류 정책·DB 무변경을 확인한다.",
        "1. 오류 토큰으로 연결/해제를 시도한다.",
        "[DB 확인 예시]\ntbl_sns_info: 무단 변경 없음",
    ),
    row(
        "008",
        "구글 SNS 연동",
        "해제 시 sns_account_id 잔존 없음",
        "해제 성공 후 sns_account_id가 남지 않음을 확인한다.",
        "1. 해제 후 tbl_sns_info sns_type=6 행 부재를 확인한다.",
        "[DB 확인 예시]\ntbl_sns_info: sns_type=6 행 0건",
    ),
    row(
        "008",
        "구글 SNS 연동",
        "ActionLog 실패가 본 처리 롤백 안 함",
        "ActionLog 기록 실패가 연동 저장/삭제를 롤백하지 않음을 확인한다.",
        "1. ActionLog 실패 mock 후 연결 성공·DB 저장을 확인한다.",
        "[DB 확인 예시]\ntbl_sns_info: 저장 유지 (FR-009)",
    ),
]

# ========== 009 sns-profile-aud-verify (22+) ==========
rows += [
    row(
        "009",
        "SNS aud 검증",
        "구글 프로필 API aud 일치 성공",
        "tbl_sns_config(sns_type=6, app_type=all, client_id) 일치 시 프로필 성공을 확인한다.",
        "1. tbl_sns_config에 G_CLIENT 행을 확인한다.\n2. aud=G_CLIENT id_token으로 프로필 API를 호출한다.",
        "[요청 예시]\nPOST /v1/api/account/sns/google/profile\n{\"clientId\": \"G_CLIENT\", \"idToken\": \"{valid_id_token}\"}\n\n[기대 응답 예시]\nresultcode: 200",
    ),
    row(
        "009",
        "SNS aud 검증",
        "구글 aud 불일치 744",
        "id_token aud≠tbl_sns_config.client_id 시 744를 확인한다.",
        "1. aud 불일치 토큰으로 프로필·연결 Y를 호출한다.",
        "[기대 응답 예시]\nresultcode: 744\n\n[DB 확인 예시]\ntbl_sns_info: 저장 없음",
    ),
    row(
        "009",
        "SNS aud 검증",
        "구글 tbl_sns_config 행 없음 803",
        "sns_type=6·app_type=all·client_id 불일치·0건 시 803을 확인한다.",
        "1. 미등록 clientId로 구글 프로필을 호출한다.",
        "[기대 응답 예시]\nresultcode: 803",
    ),
    row(
        "009",
        "SNS aud 검증",
        "구글 FR-009 DB 조회 선행 후 Verifier",
        "DB 조회(803) 선행 → GoogleIdTokenVerifier(744) 순서를 확인한다.",
        "1. DB 행 없음·무효 토큰 각각 호출하여 선행 실패 코드를 확인한다.",
        "[기대 응답 예시]\n행 없음: 803 (Verifier 전)\n토큰 실패: 744",
    ),
    row(
        "009",
        "SNS aud 검증",
        "애플 플랫폼 행 aud 일치 성공",
        "OAuth app_type=ios·tbl_sns_config ios 행과 aud 일치 시 성공을 확인한다.",
        "1. 12.3 sns_type=5·active_yn=Y로 연결한다.",
        "[DB 확인 예시]\ntbl_sns_config: sns_type=5, app_type=ios, client_id=IOS_CLIENT",
    ),
    row(
        "009",
        "SNS aud 검증",
        "애플 aud 불일치 718",
        "aud≠확정 client_id 시 718을 확인한다.",
        "1. aud 불일치 애플 id_token으로 연결 Y를 호출한다.",
        "[기대 응답 예시]\nresultcode: 718",
    ),
    row(
        "009",
        "SNS aud 검증",
        "애플 app_type=all 폴백 성공",
        "플랫폼 행 없음·all 행 존재 시 all 폴백으로 성공을 확인한다.",
        "1. app_type=ios 행 없음·all 행만 있는 환경에서 연결한다.",
        "[기대 응답 예시]\n프로필 파싱 성공 (all 폴백)",
    ),
    row(
        "009",
        "SNS aud 검증",
        "애플 설정 없음 803",
        "플랫폼·all 행 모두 없음 시 803을 확인한다.",
        "1. tbl_sns_config 0건 환경에서 애플 연결 Y를 호출한다.",
        "[기대 응답 예시]\nresultcode: 803",
    ),
    row(
        "009",
        "SNS aud 검증",
        "애플 동일 app_type client_id 2건 이상 746",
        "svc_type+app_type에 client_id 2건 이상 시 746을 확인한다.",
        "1. 중복 client_id 행 환경에서 애플 aud 검증을 호출한다.",
        "[기대 응답 예시]\nresultcode: 746",
    ),
    row(
        "009",
        "SNS aud 검증",
        "clientId validation 실패 750",
        "요청 clientId 형식·필수값 실패 시 750을 확인한다.",
        "1. clientId 누락·무효로 프로필 API를 호출한다.",
        "[기대 응답 예시]\nresultcode: 750",
    ),
    row(
        "009",
        "구글 refresh_token",
        "12.3 구글 Y refreshToken 필수 저장",
        "active_yn=Y·sns_type=6 시 refreshToken 필수·revoke_refresh_token 저장을 확인한다.",
        "1. refreshToken 포함 12.3 Y를 호출한다.",
        "[요청 예시]\nPOST /v1/api/account/snsinfo\n{\"sns_type\":6,\"active_yn\":\"Y\",\"sns_token\":\"{id_token}\",\"refresh_token\":\"{google_refresh_token}\",\"client_id\":\"{client_id}\"}\n\n[DB 확인 예시]\ntbl_sns_info.revoke_refresh_token: {google_refresh_token}",
    ),
    row(
        "009",
        "구글 refresh_token",
        "12.3 구글 Y refreshToken 누락 HTTP 400",
        "refreshToken 누락·blank 시 HTTP 400 validation을 확인한다.",
        "1. refreshToken 없이 12.3 구글 Y를 호출한다.",
        "[기대 응답 예시]\nHTTP 400\nmessage: 유효성 검사 실패 : refresh_token\n\n[DB 확인 예시]\nrevoke_refresh_token 저장 없음",
    ),
    row(
        "009",
        "구글 연동 해제",
        "12.3 구글 N 조기 disconnect (aud·프로필 없음)",
        "구글 N은 fetchProfile·aud 검증 없이 조기 disconnect함을 확인한다.",
        "1. 연동 행으로 12.3 N(sns_token=id_token 가능)을 호출한다.\n2. 프로필 API 미호출·DB revoke_refresh_token만 사용을 확인한다.",
        "[요청 예시]\nPOST /v1/api/account/snsinfo\n{\"sns_type\":6,\"active_yn\":\"N\",\"sns_token\":\"{id_token}\",...}\n(refreshToken·sns_token은 revoke 미사용)",
    ),
    row(
        "009",
        "구글 연동 해제",
        "12.3 구글 N DB revoke_refresh_token으로 revoke",
        "해제 N 시 DB revoke_refresh_token만으로 Google revoke 후 DELETE를 확인한다.",
        "1. revoke_refresh_token 저장된 행으로 12.3 N을 호출한다.",
        "[기대 응답 예시]\nresultcode: 200\n\n[DB 확인 예시]\ntbl_sns_info: 행 삭제",
    ),
    row(
        "009",
        "구글 연동 해제",
        "12.3 구글 N revoke_refresh_token blank 745",
        "DB revoke_refresh_token null/blank 시 745·행 유지를 확인한다.",
        "1. 레거시 행(revoke_refresh_token 없음)으로 12.3 N을 호출한다.",
        "[기대 응답 예시]\nresultcode: 745\n\n[DB 확인 예시]\ntbl_sns_info: 행 유지",
    ),
    row(
        "009",
        "구글 연동 해제",
        "12.3 구글 N revoke Feign 실패 745",
        "Google revoke API 실패 시 745·행 유지를 확인한다.",
        "1. revoke 실패 mock으로 12.3 N을 호출한다.",
        "[기대 응답 예시]\nresultcode: 745",
    ),
    row(
        "009",
        "SNS aud 검증",
        "네이버·카카오 aud 검증 미적용",
        "sns_type 3·4 프로필 경로에 aud 로직이 없음을 확인한다.",
        "1. 네이버·카카오 연결 Y를 호출한다.\n2. tbl_sns_config aud 조회 없이 기존 동작임을 확인한다.",
        "[기대 응답 예시]\n기존 004 brownfield 동작 (aud 없음)",
    ),
    row(
        "009",
        "SNS aud 검증",
        "6.20 구글·애플 Y aud 검증 적용",
        "6.20 active_yn=Y 시 구글§2·애플§3 aud 경로를 확인한다.",
        "1. 6.20 구글·애플 Y 연결을 각각 호출한다.",
        "[기대 응답 예시]\naud 실패: 803/744/718",
    ),
    row(
        "009",
        "SNS aud 검증",
        "애플 revoke client_id FR-003-Apple resolver",
        "애플 revoke·client_secret JWT sub에 FR-003-Apple 확정 client_id 사용을 확인한다.",
        "1. 12.3 애플 N revoke 호출 시 client_id 출처를 확인한다.",
        "[기대 응답 예시]\nrevoke 실패: 722",
    ),
    row(
        "009",
        "SNS aud 검증",
        "aud 실패 시 후속 부작용 없음",
        "aud 검증 실패 시 저장·revoke·ActionLog 후속 없음을 확인한다(FR-010).",
        "1. aud 불일치로 연결 Y를 호출한다.",
        "[DB 확인 예시]\ntbl_sns_info: 변경 없음",
    ),
    row(
        "009",
        "SNS aud 검증",
        "GoogleAuthConfig allowlist 폐지",
        "008 GOOGLE_CLIENT_ID allowlist 미사용·tbl_sns_config SSOT를 확인한다.",
        "1. ConfigMap allowlist 없이 tbl_sns_config만으로 aud 검증 성공을 확인한다.",
        "[기대 응답 예시]\ntbl_sns_config.client_id 기준 검증",
    ),
    row(
        "009",
        "구글 refresh_token",
        "6.20 구글 refreshToken·revoke_refresh_token 없음",
        "6.20 구글 Y에 refreshToken 필수·DB 저장 규칙 미적용(Out of scope)을 확인한다.",
        "1. 6.20 구글 Y( refreshToken 없음) 호출 시 009 FR-012 미적용을 확인한다.",
        "[기대 응답 예시]\n6.20: refreshToken 필수 아님 (12.3만 FR-012)",
    ),
    row(
        "009",
        "SNS aud 검증",
        "구글 다중 audience 배열 aud 정합",
        "id_token aud 배열에 tbl_sns_config.client_id 포함 시 통과를 확인한다.",
        "1. 다중 aud 배열 토큰으로 프로필 API를 호출한다.",
        "[기대 응답 예시]\nresultcode: 200 (배열에 client_id 포함 시)",
    ),
]

# ========== 010 google-risc-receive (12) ==========
rows += [
    row(
        "010",
        "Google RISC 수신",
        "tokens-revoked 유효 JWT 행 삭제 HTTP 202",
        "tokens-revoked·subject.sub 매칭 시 sns_type=6 행 삭제·HTTP 202를 확인한다.",
        "1. tbl_sns_info sns_type=6 행을 준비한다.\n2. POST /v1/account/sns/google/disconnect-receive 에 SET JWT body를 보낸다.\n3. HTTP 202·행 삭제를 확인한다.",
        "[요청 예시]\nPOST /v1/account/sns/google/disconnect-receive\nContent-Type: application/secevent+jwt\n{signed_jwt_compact}\n\n[기대 응답 예시]\nHTTP 202\n\n[DB 확인 예시]\ntbl_sns_info: sns_type=6, sns_id=subject.sub — 행 삭제",
    ),
    row(
        "010",
        "Google RISC 수신",
        "token-revoked 유효 JWT 행 삭제 HTTP 202",
        "token-revoked 이벤트도 동일 삭제·HTTP 202를 확인한다.",
        "1. token-revoked JWT로 POST한다.",
        "[기대 응답 예시]\nHTTP 202",
    ),
    row(
        "010",
        "Google RISC 수신",
        "검증 성공·매칭 행 없음 no-op HTTP 202",
        "매칭 행 없을 때 no-op·HTTP 202를 확인한다.",
        "1. DB에 없는 sub로 유효 JWT를 POST한다.",
        "[기대 응답 예시]\nHTTP 202 (no-op)",
    ),
    row(
        "010",
        "Google RISC 수신",
        "subject.sub 없음·blank HTTP 400",
        "처리 대상 이벤트에 sub 없음 시 HTTP 400·DB 미변경을 확인한다.",
        "1. sub 누락 JWT로 POST한다.",
        "[기대 응답 예시]\nHTTP 400\n\n[DB 확인 예시]\ntbl_sns_info: 변경 없음",
    ),
    row(
        "010",
        "Google RISC 수신",
        "aud 불일치 HTTP 401",
        "aud≠tbl_sns_config client_id 시 HTTP 401을 확인한다.",
        "1. aud 불일치 JWT로 POST한다.",
        "[기대 응답 예시]\nHTTP 401",
    ),
    row(
        "010",
        "Google RISC 수신",
        "iss 불일치 HTTP 401",
        "iss가 https://accounts.google.com(/) 외 시 HTTP 401을 확인한다.",
        "1. iss 불일치 JWT로 POST한다.",
        "[기대 응답 예시]\nHTTP 401",
    ),
    row(
        "010",
        "Google RISC 수신",
        "body 없음·JWT 형식 오류 HTTP 400",
        "body 없음·blank·비 compact JWT 시 HTTP 400을 확인한다.",
        "1. 빈 body 또는 잘못된 형식으로 POST한다.",
        "[기대 응답 예시]\nHTTP 400",
    ),
    row(
        "010",
        "Google RISC 수신",
        "설정·DB 장애 HTTP 500",
        "RISC 필수 설정 없음·DB 오류 시 HTTP 500을 확인한다.",
        "1. DB 장애 환경에서 유효 JWT를 POST한다.",
        "[기대 응답 예시]\nHTTP 500",
    ),
    row(
        "010",
        "Google RISC 수신",
        "삭제 후 12.2 구글 미연결",
        "RISC 삭제 후 12.2에서 sns_type=6 beforeConn=0·빈 snsId를 확인한다.",
        "1. RISC 삭제 후 GET /v1/api/account/snsinfo 를 호출한다.",
        "[기대 응답 예시]\nsns_type=6: beforeConn=0, snsId=\"\"",
    ),
    row(
        "010",
        "Google RISC 수신",
        "동일 알림 재전송 멱등 HTTP 202",
        "이미 삭제된 후 재전송 시 no-op·HTTP 202를 확인한다.",
        "1. 삭제 후 동일 JWT를 재POST한다.",
        "[기대 응답 예시]\nHTTP 202 (멱등)",
    ),
    row(
        "010",
        "Google RISC 수신",
        "비대상 이벤트만 포함 HTTP 202",
        "verification 등 비대상 이벤트만 있으면 DELETE 없이 HTTP 202를 확인한다.",
        "1. verification만 포함 JWT를 POST한다.",
        "[기대 응답 예시]\nHTTP 202\nDELETE 없음",
    ),
    row(
        "010",
        "Google RISC 수신",
        "mixed events 처리 대상 sub만 DELETE",
        "처리 대상·비대상 이벤트 혼합 시 대상 sub만 DELETE·HTTP 202를 확인한다.",
        "1. tokens-revoked+verification 혼합 JWT를 POST한다.",
        "[기대 응답 예시]\nHTTP 202\n처리 대상 sub만 DELETE",
    ),
]

counts = {}
for r in rows:
    counts[r["spec"]] = counts.get(r["spec"], 0) + 1

mins = {"002": 14, "006": 25, "007": 25, "008": 22, "009": 22, "010": 12}
issues = []
for s, m in mins.items():
    if counts.get(s, 0) < m:
        issues.append(f"spec {s}: {counts.get(s,0)} < minimum {m}")

OUT.write_text(json.dumps(rows, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"Wrote {len(rows)} rows to {OUT}")
for s in sorted(counts):
    print(f"  spec {s}: {counts[s]}")
if issues:
    print("ISSUES:", "; ".join(issues))
else:
    print("All minimum counts met.")
