--
-- PostgreSQL database dump
--

\restrict moneylogdumpkey

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: moneylog; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA moneylog;


--
-- Name: seq_installment_group; Type: SEQUENCE; Schema: moneylog; Owner: -
--

CREATE SEQUENCE moneylog.seq_installment_group
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: tbl_user; Type: TABLE; Schema: moneylog; Owner: -
--

CREATE TABLE moneylog.tbl_user (
    id_key bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint,
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by bigint,
    active boolean DEFAULT true NOT NULL,
    email character varying(100),
    intro character varying(500),
    nickname character varying(20) NOT NULL,
    phone character varying(20),
    pw character varying(100) NOT NULL,
    role smallint DEFAULT 3 NOT NULL,
    user_id character varying(20) NOT NULL,
    CONSTRAINT ck_user_role CHECK ((role = ANY (ARRAY[1, 3])))
);


--
-- Name: tbl_user_expend_group; Type: TABLE; Schema: moneylog; Owner: -
--

CREATE TABLE moneylog.tbl_user_expend_group (
    idx bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by bigint NOT NULL,
    default_group boolean DEFAULT false NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    icon_filename character varying(255),
    in_use boolean DEFAULT true NOT NULL,
    name character varying(30) NOT NULL,
    id_key bigint NOT NULL
);


--
-- Name: tbl_user_expend_group_idx_seq; Type: SEQUENCE; Schema: moneylog; Owner: -
--

ALTER TABLE moneylog.tbl_user_expend_group ALTER COLUMN idx ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME moneylog.tbl_user_expend_group_idx_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user_expend_target_default; Type: TABLE; Schema: moneylog; Owner: -
--

CREATE TABLE moneylog.tbl_user_expend_target_default (
    idx bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by bigint NOT NULL,
    target_amount bigint NOT NULL,
    expend_group_idx bigint NOT NULL,
    id_key bigint NOT NULL,
    CONSTRAINT ck_target_default_amount CHECK (((target_amount >= 0) AND (target_amount <= 100000000)))
);


--
-- Name: tbl_user_expend_target_default_idx_seq; Type: SEQUENCE; Schema: moneylog; Owner: -
--

ALTER TABLE moneylog.tbl_user_expend_target_default ALTER COLUMN idx ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME moneylog.tbl_user_expend_target_default_idx_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user_expend_target_monthly; Type: TABLE; Schema: moneylog; Owner: -
--

CREATE TABLE moneylog.tbl_user_expend_target_monthly (
    idx bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by bigint NOT NULL,
    month integer NOT NULL,
    target_amount bigint NOT NULL,
    year integer NOT NULL,
    expend_group_idx bigint NOT NULL,
    id_key bigint NOT NULL,
    CONSTRAINT ck_target_monthly_amount CHECK (((target_amount >= 0) AND (target_amount <= 100000000))),
    CONSTRAINT ck_target_monthly_month CHECK (((month >= 1) AND (month <= 12)))
);


--
-- Name: tbl_user_expend_target_monthly_idx_seq; Type: SEQUENCE; Schema: moneylog; Owner: -
--

ALTER TABLE moneylog.tbl_user_expend_target_monthly ALTER COLUMN idx ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME moneylog.tbl_user_expend_target_monthly_idx_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user_expense; Type: TABLE; Schema: moneylog; Owner: -
--

CREATE TABLE moneylog.tbl_user_expense (
    idx bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by bigint NOT NULL,
    amount bigint NOT NULL,
    content character varying(255) NOT NULL,
    expend_group_name character varying(30) NOT NULL,
    installment_group_id bigint,
    installment_index integer,
    installment_total integer,
    payment_date date NOT NULL,
    payment_method_name character varying(50) NOT NULL,
    place character varying(100) NOT NULL,
    expend_group_idx bigint NOT NULL,
    payment_method_idx bigint NOT NULL,
    id_key bigint NOT NULL,
    CONSTRAINT ck_expense_amount CHECK ((amount > 0)),
    CONSTRAINT ck_expense_installment_index CHECK (((installment_index IS NULL) OR (installment_index >= 1))),
    CONSTRAINT ck_expense_installment_total CHECK (((installment_total IS NULL) OR (installment_total >= 2)))
);


--
-- Name: tbl_user_expense_idx_seq; Type: SEQUENCE; Schema: moneylog; Owner: -
--

ALTER TABLE moneylog.tbl_user_expense ALTER COLUMN idx ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME moneylog.tbl_user_expense_idx_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user_fixed_expense; Type: TABLE; Schema: moneylog; Owner: -
--

CREATE TABLE moneylog.tbl_user_fixed_expense (
    idx bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by bigint NOT NULL,
    amount bigint NOT NULL,
    content character varying(255) NOT NULL,
    end_month integer NOT NULL,
    end_year integer NOT NULL,
    name character varying(50) NOT NULL,
    payment_day_of_month integer NOT NULL,
    start_month integer NOT NULL,
    start_year integer NOT NULL,
    expend_group_idx bigint NOT NULL,
    payment_method_idx bigint NOT NULL,
    id_key bigint NOT NULL,
    CONSTRAINT ck_fixed_expense_amount CHECK ((amount > 0)),
    CONSTRAINT ck_fixed_expense_day CHECK (((payment_day_of_month >= 1) AND (payment_day_of_month <= 31))),
    CONSTRAINT ck_fixed_expense_end_month CHECK (((end_month >= 1) AND (end_month <= 12))),
    CONSTRAINT ck_fixed_expense_period CHECK ((((end_year * 12) + end_month) >= ((start_year * 12) + start_month))),
    CONSTRAINT ck_fixed_expense_start_month CHECK (((start_month >= 1) AND (start_month <= 12)))
);


--
-- Name: tbl_user_fixed_expense_idx_seq; Type: SEQUENCE; Schema: moneylog; Owner: -
--

ALTER TABLE moneylog.tbl_user_fixed_expense ALTER COLUMN idx ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME moneylog.tbl_user_fixed_expense_idx_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user_fixed_expense_monthly; Type: TABLE; Schema: moneylog; Owner: -
--

CREATE TABLE moneylog.tbl_user_fixed_expense_monthly (
    idx bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by bigint NOT NULL,
    amount bigint NOT NULL,
    content character varying(255) NOT NULL,
    modified boolean DEFAULT false NOT NULL,
    month integer NOT NULL,
    payment_date date NOT NULL,
    year integer NOT NULL,
    expend_group_idx bigint NOT NULL,
    fixed_expense_idx bigint NOT NULL,
    payment_method_idx bigint NOT NULL,
    id_key bigint NOT NULL,
    CONSTRAINT ck_fixed_monthly_amount CHECK ((amount > 0)),
    CONSTRAINT ck_fixed_monthly_month CHECK (((month >= 1) AND (month <= 12)))
);


--
-- Name: tbl_user_fixed_expense_monthly_idx_seq; Type: SEQUENCE; Schema: moneylog; Owner: -
--

ALTER TABLE moneylog.tbl_user_fixed_expense_monthly ALTER COLUMN idx ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME moneylog.tbl_user_fixed_expense_monthly_idx_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user_id_key_seq; Type: SEQUENCE; Schema: moneylog; Owner: -
--

ALTER TABLE moneylog.tbl_user ALTER COLUMN id_key ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME moneylog.tbl_user_id_key_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user_income; Type: TABLE; Schema: moneylog; Owner: -
--

CREATE TABLE moneylog.tbl_user_income (
    idx bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by bigint NOT NULL,
    amount bigint NOT NULL,
    content character varying(255),
    payment_date date NOT NULL,
    payment_method_name character varying(50) NOT NULL,
    payment_method_idx bigint NOT NULL,
    id_key bigint NOT NULL,
    CONSTRAINT ck_income_amount CHECK ((amount > 0))
);


--
-- Name: tbl_user_income_idx_seq; Type: SEQUENCE; Schema: moneylog; Owner: -
--

ALTER TABLE moneylog.tbl_user_income ALTER COLUMN idx ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME moneylog.tbl_user_income_idx_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user_login_history; Type: TABLE; Schema: moneylog; Owner: -
--

CREATE TABLE moneylog.tbl_user_login_history (
    idx bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by bigint NOT NULL,
    login_at timestamp(6) with time zone NOT NULL,
    login_ip character varying(45),
    id_key bigint NOT NULL
);


--
-- Name: tbl_user_login_history_idx_seq; Type: SEQUENCE; Schema: moneylog; Owner: -
--

ALTER TABLE moneylog.tbl_user_login_history ALTER COLUMN idx ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME moneylog.tbl_user_login_history_idx_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user_payment_method; Type: TABLE; Schema: moneylog; Owner: -
--

CREATE TABLE moneylog.tbl_user_payment_method (
    idx bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by bigint NOT NULL,
    card_expiry character(7),
    deleted boolean DEFAULT false NOT NULL,
    in_use boolean DEFAULT true NOT NULL,
    name character varying(50) NOT NULL,
    purpose character varying(10) NOT NULL,
    type character varying(10) NOT NULL,
    id_key bigint NOT NULL,
    CONSTRAINT ck_payment_method_purpose CHECK (((purpose)::text = ANY ((ARRAY['EXPENSE'::character varying, 'INCOME'::character varying])::text[]))),
    CONSTRAINT ck_payment_method_type CHECK (((type)::text = ANY ((ARRAY['CARD'::character varying, 'ACCOUNT'::character varying])::text[])))
);


--
-- Name: tbl_user_payment_method_idx_seq; Type: SEQUENCE; Schema: moneylog; Owner: -
--

ALTER TABLE moneylog.tbl_user_payment_method ALTER COLUMN idx ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME moneylog.tbl_user_payment_method_idx_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user_session; Type: TABLE; Schema: moneylog; Owner: -
--

CREATE TABLE moneylog.tbl_user_session (
    idx bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by bigint NOT NULL,
    access_expires_at timestamp(6) with time zone NOT NULL,
    access_token_hash character varying(100),
    last_accessed_at timestamp(6) with time zone,
    refresh_expires_at timestamp(6) with time zone NOT NULL,
    refresh_token_hash character varying(100),
    revoked boolean DEFAULT false NOT NULL,
    session_id uuid NOT NULL,
    id_key bigint NOT NULL
);


--
-- Name: tbl_user_session_idx_seq; Type: SEQUENCE; Schema: moneylog; Owner: -
--

ALTER TABLE moneylog.tbl_user_session ALTER COLUMN idx ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME moneylog.tbl_user_session_idx_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user_statistics; Type: TABLE; Schema: moneylog; Owner: -
--

CREATE TABLE moneylog.tbl_user_statistics (
    idx bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by bigint NOT NULL,
    expense_total bigint NOT NULL,
    fixed_amount bigint NOT NULL,
    fixed_percent numeric(5,2) NOT NULL,
    income_total bigint NOT NULL,
    month integer NOT NULL,
    regular_amount bigint NOT NULL,
    regular_percent numeric(5,2) NOT NULL,
    saved_at timestamp(6) with time zone NOT NULL,
    year integer NOT NULL,
    id_key bigint NOT NULL,
    CONSTRAINT ck_statistics_month CHECK (((month >= 1) AND (month <= 12)))
);


--
-- Name: tbl_user_statistics_expend_group; Type: TABLE; Schema: moneylog; Owner: -
--

CREATE TABLE moneylog.tbl_user_statistics_expend_group (
    idx bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by bigint NOT NULL,
    amount bigint NOT NULL,
    expend_group_idx bigint NOT NULL,
    expend_group_name character varying(30) NOT NULL,
    status character varying(10) NOT NULL,
    target_amount bigint NOT NULL,
    usage_rate numeric(6,2) NOT NULL,
    statistics_idx bigint NOT NULL,
    id_key bigint NOT NULL,
    CONSTRAINT ck_stat_group_status CHECK (((status)::text = ANY ((ARRAY['UNDER'::character varying, 'OK'::character varying, 'OVER'::character varying])::text[])))
);


--
-- Name: tbl_user_statistics_expend_group_idx_seq; Type: SEQUENCE; Schema: moneylog; Owner: -
--

ALTER TABLE moneylog.tbl_user_statistics_expend_group ALTER COLUMN idx ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME moneylog.tbl_user_statistics_expend_group_idx_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user_statistics_idx_seq; Type: SEQUENCE; Schema: moneylog; Owner: -
--

ALTER TABLE moneylog.tbl_user_statistics ALTER COLUMN idx ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME moneylog.tbl_user_statistics_idx_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user_statistics_payment_method; Type: TABLE; Schema: moneylog; Owner: -
--

CREATE TABLE moneylog.tbl_user_statistics_payment_method (
    idx bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by bigint NOT NULL,
    amount bigint NOT NULL,
    payment_method_idx bigint NOT NULL,
    payment_method_name character varying(50) NOT NULL,
    statistics_idx bigint NOT NULL,
    id_key bigint NOT NULL
);


--
-- Name: tbl_user_statistics_payment_method_idx_seq; Type: SEQUENCE; Schema: moneylog; Owner: -
--

ALTER TABLE moneylog.tbl_user_statistics_payment_method ALTER COLUMN idx ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME moneylog.tbl_user_statistics_payment_method_idx_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user_statistics_weekly; Type: TABLE; Schema: moneylog; Owner: -
--

CREATE TABLE moneylog.tbl_user_statistics_weekly (
    idx bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by bigint NOT NULL,
    amount bigint NOT NULL,
    week_end date NOT NULL,
    week_index integer NOT NULL,
    week_start date NOT NULL,
    statistics_idx bigint NOT NULL,
    id_key bigint NOT NULL,
    CONSTRAINT ck_stat_weekly_index CHECK ((week_index >= 1))
);


--
-- Name: tbl_user_statistics_weekly_idx_seq; Type: SEQUENCE; Schema: moneylog; Owner: -
--

ALTER TABLE moneylog.tbl_user_statistics_weekly ALTER COLUMN idx ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME moneylog.tbl_user_statistics_weekly_idx_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user_expend_group tbl_user_expend_group_pkey; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_expend_group
    ADD CONSTRAINT tbl_user_expend_group_pkey PRIMARY KEY (idx);


--
-- Name: tbl_user_expend_target_default tbl_user_expend_target_default_pkey; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_expend_target_default
    ADD CONSTRAINT tbl_user_expend_target_default_pkey PRIMARY KEY (idx);


--
-- Name: tbl_user_expend_target_monthly tbl_user_expend_target_monthly_pkey; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_expend_target_monthly
    ADD CONSTRAINT tbl_user_expend_target_monthly_pkey PRIMARY KEY (idx);


--
-- Name: tbl_user_expense tbl_user_expense_pkey; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_expense
    ADD CONSTRAINT tbl_user_expense_pkey PRIMARY KEY (idx);


--
-- Name: tbl_user_fixed_expense_monthly tbl_user_fixed_expense_monthly_pkey; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_fixed_expense_monthly
    ADD CONSTRAINT tbl_user_fixed_expense_monthly_pkey PRIMARY KEY (idx);


--
-- Name: tbl_user_fixed_expense tbl_user_fixed_expense_pkey; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_fixed_expense
    ADD CONSTRAINT tbl_user_fixed_expense_pkey PRIMARY KEY (idx);


--
-- Name: tbl_user_income tbl_user_income_pkey; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_income
    ADD CONSTRAINT tbl_user_income_pkey PRIMARY KEY (idx);


--
-- Name: tbl_user_login_history tbl_user_login_history_pkey; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_login_history
    ADD CONSTRAINT tbl_user_login_history_pkey PRIMARY KEY (idx);


--
-- Name: tbl_user_payment_method tbl_user_payment_method_pkey; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_payment_method
    ADD CONSTRAINT tbl_user_payment_method_pkey PRIMARY KEY (idx);


--
-- Name: tbl_user tbl_user_pkey; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user
    ADD CONSTRAINT tbl_user_pkey PRIMARY KEY (id_key);


--
-- Name: tbl_user_session tbl_user_session_pkey; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_session
    ADD CONSTRAINT tbl_user_session_pkey PRIMARY KEY (idx);


--
-- Name: tbl_user_statistics_expend_group tbl_user_statistics_expend_group_pkey; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_statistics_expend_group
    ADD CONSTRAINT tbl_user_statistics_expend_group_pkey PRIMARY KEY (idx);


--
-- Name: tbl_user_statistics_payment_method tbl_user_statistics_payment_method_pkey; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_statistics_payment_method
    ADD CONSTRAINT tbl_user_statistics_payment_method_pkey PRIMARY KEY (idx);


--
-- Name: tbl_user_statistics tbl_user_statistics_pkey; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_statistics
    ADD CONSTRAINT tbl_user_statistics_pkey PRIMARY KEY (idx);


--
-- Name: tbl_user_statistics_weekly tbl_user_statistics_weekly_pkey; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_statistics_weekly
    ADD CONSTRAINT tbl_user_statistics_weekly_pkey PRIMARY KEY (idx);


--
-- Name: tbl_user_expend_group ux_user_expend_group_name; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_expend_group
    ADD CONSTRAINT ux_user_expend_group_name UNIQUE (id_key, name);


--
-- Name: tbl_user_fixed_expense_monthly ux_user_fixed_expense_monthly; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_fixed_expense_monthly
    ADD CONSTRAINT ux_user_fixed_expense_monthly UNIQUE (fixed_expense_idx, year, month);


--
-- Name: tbl_user_session ux_user_session_id; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_session
    ADD CONSTRAINT ux_user_session_id UNIQUE (session_id);


--
-- Name: tbl_user_statistics_expend_group ux_user_stat_group; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_statistics_expend_group
    ADD CONSTRAINT ux_user_stat_group UNIQUE (statistics_idx, expend_group_idx);


--
-- Name: tbl_user_statistics_payment_method ux_user_stat_method; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_statistics_payment_method
    ADD CONSTRAINT ux_user_stat_method UNIQUE (statistics_idx, payment_method_idx);


--
-- Name: tbl_user_statistics_weekly ux_user_stat_weekly; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_statistics_weekly
    ADD CONSTRAINT ux_user_stat_weekly UNIQUE (statistics_idx, week_index);


--
-- Name: tbl_user_statistics ux_user_statistics; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_statistics
    ADD CONSTRAINT ux_user_statistics UNIQUE (id_key, year, month);


--
-- Name: tbl_user_expend_target_default ux_user_target_default; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_expend_target_default
    ADD CONSTRAINT ux_user_target_default UNIQUE (id_key, expend_group_idx);


--
-- Name: tbl_user_expend_target_monthly ux_user_target_monthly; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_expend_target_monthly
    ADD CONSTRAINT ux_user_target_monthly UNIQUE (id_key, year, month, expend_group_idx);


--
-- Name: tbl_user ux_user_user_id; Type: CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user
    ADD CONSTRAINT ux_user_user_id UNIQUE (user_id);


--
-- Name: ix_user_expend_group_active; Type: INDEX; Schema: moneylog; Owner: -
--

CREATE INDEX ix_user_expend_group_active ON moneylog.tbl_user_expend_group USING btree (id_key, in_use, deleted);


--
-- Name: ix_user_expense_date; Type: INDEX; Schema: moneylog; Owner: -
--

CREATE INDEX ix_user_expense_date ON moneylog.tbl_user_expense USING btree (id_key, payment_date);


--
-- Name: ix_user_expense_installment; Type: INDEX; Schema: moneylog; Owner: -
--

CREATE INDEX ix_user_expense_installment ON moneylog.tbl_user_expense USING btree (installment_group_id, payment_date);


--
-- Name: ix_user_fixed_expense_period; Type: INDEX; Schema: moneylog; Owner: -
--

CREATE INDEX ix_user_fixed_expense_period ON moneylog.tbl_user_fixed_expense USING btree (id_key, start_year, start_month, end_year, end_month);


--
-- Name: ix_user_fixed_monthly_ym; Type: INDEX; Schema: moneylog; Owner: -
--

CREATE INDEX ix_user_fixed_monthly_ym ON moneylog.tbl_user_fixed_expense_monthly USING btree (id_key, year, month);


--
-- Name: ix_user_income_date; Type: INDEX; Schema: moneylog; Owner: -
--

CREATE INDEX ix_user_income_date ON moneylog.tbl_user_income USING btree (id_key, payment_date);


--
-- Name: ix_user_login_history_at; Type: INDEX; Schema: moneylog; Owner: -
--

CREATE INDEX ix_user_login_history_at ON moneylog.tbl_user_login_history USING btree (id_key, login_at);


--
-- Name: ix_user_payment_method_active; Type: INDEX; Schema: moneylog; Owner: -
--

CREATE INDEX ix_user_payment_method_active ON moneylog.tbl_user_payment_method USING btree (id_key, purpose, in_use, deleted);


--
-- Name: ux_user_email; Type: INDEX; Schema: moneylog; Owner: -
--

CREATE UNIQUE INDEX ux_user_email ON moneylog.tbl_user USING btree (email) WHERE (email IS NOT NULL);


--
-- Name: ux_user_session_active; Type: INDEX; Schema: moneylog; Owner: -
--

CREATE UNIQUE INDEX ux_user_session_active ON moneylog.tbl_user_session USING btree (id_key) WHERE (revoked = false);


--
-- Name: tbl_user_expend_group fk_user_expend_group_user; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_expend_group
    ADD CONSTRAINT fk_user_expend_group_user FOREIGN KEY (id_key) REFERENCES moneylog.tbl_user(id_key);


--
-- Name: tbl_user_expense fk_user_expense_expend_group; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_expense
    ADD CONSTRAINT fk_user_expense_expend_group FOREIGN KEY (expend_group_idx) REFERENCES moneylog.tbl_user_expend_group(idx);


--
-- Name: tbl_user_expense fk_user_expense_payment_method; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_expense
    ADD CONSTRAINT fk_user_expense_payment_method FOREIGN KEY (payment_method_idx) REFERENCES moneylog.tbl_user_payment_method(idx);


--
-- Name: tbl_user_expense fk_user_expense_user; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_expense
    ADD CONSTRAINT fk_user_expense_user FOREIGN KEY (id_key) REFERENCES moneylog.tbl_user(id_key);


--
-- Name: tbl_user_fixed_expense fk_user_fixed_expense_expend_group; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_fixed_expense
    ADD CONSTRAINT fk_user_fixed_expense_expend_group FOREIGN KEY (expend_group_idx) REFERENCES moneylog.tbl_user_expend_group(idx);


--
-- Name: tbl_user_fixed_expense fk_user_fixed_expense_payment_method; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_fixed_expense
    ADD CONSTRAINT fk_user_fixed_expense_payment_method FOREIGN KEY (payment_method_idx) REFERENCES moneylog.tbl_user_payment_method(idx);


--
-- Name: tbl_user_fixed_expense fk_user_fixed_expense_user; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_fixed_expense
    ADD CONSTRAINT fk_user_fixed_expense_user FOREIGN KEY (id_key) REFERENCES moneylog.tbl_user(id_key);


--
-- Name: tbl_user_fixed_expense_monthly fk_user_fixed_monthly_expend_group; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_fixed_expense_monthly
    ADD CONSTRAINT fk_user_fixed_monthly_expend_group FOREIGN KEY (expend_group_idx) REFERENCES moneylog.tbl_user_expend_group(idx);


--
-- Name: tbl_user_fixed_expense_monthly fk_user_fixed_monthly_fixed_expense; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_fixed_expense_monthly
    ADD CONSTRAINT fk_user_fixed_monthly_fixed_expense FOREIGN KEY (fixed_expense_idx) REFERENCES moneylog.tbl_user_fixed_expense(idx) ON DELETE CASCADE;


--
-- Name: tbl_user_fixed_expense_monthly fk_user_fixed_monthly_payment_method; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_fixed_expense_monthly
    ADD CONSTRAINT fk_user_fixed_monthly_payment_method FOREIGN KEY (payment_method_idx) REFERENCES moneylog.tbl_user_payment_method(idx);


--
-- Name: tbl_user_fixed_expense_monthly fk_user_fixed_monthly_user; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_fixed_expense_monthly
    ADD CONSTRAINT fk_user_fixed_monthly_user FOREIGN KEY (id_key) REFERENCES moneylog.tbl_user(id_key);


--
-- Name: tbl_user_income fk_user_income_payment_method; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_income
    ADD CONSTRAINT fk_user_income_payment_method FOREIGN KEY (payment_method_idx) REFERENCES moneylog.tbl_user_payment_method(idx);


--
-- Name: tbl_user_income fk_user_income_user; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_income
    ADD CONSTRAINT fk_user_income_user FOREIGN KEY (id_key) REFERENCES moneylog.tbl_user(id_key);


--
-- Name: tbl_user_login_history fk_user_login_history_user; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_login_history
    ADD CONSTRAINT fk_user_login_history_user FOREIGN KEY (id_key) REFERENCES moneylog.tbl_user(id_key);


--
-- Name: tbl_user_payment_method fk_user_payment_method_user; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_payment_method
    ADD CONSTRAINT fk_user_payment_method_user FOREIGN KEY (id_key) REFERENCES moneylog.tbl_user(id_key);


--
-- Name: tbl_user_session fk_user_session_user; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_session
    ADD CONSTRAINT fk_user_session_user FOREIGN KEY (id_key) REFERENCES moneylog.tbl_user(id_key);


--
-- Name: tbl_user_statistics_expend_group fk_user_stat_group_statistics; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_statistics_expend_group
    ADD CONSTRAINT fk_user_stat_group_statistics FOREIGN KEY (statistics_idx) REFERENCES moneylog.tbl_user_statistics(idx) ON DELETE CASCADE;


--
-- Name: tbl_user_statistics_expend_group fk_user_stat_group_user; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_statistics_expend_group
    ADD CONSTRAINT fk_user_stat_group_user FOREIGN KEY (id_key) REFERENCES moneylog.tbl_user(id_key);


--
-- Name: tbl_user_statistics_payment_method fk_user_stat_method_statistics; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_statistics_payment_method
    ADD CONSTRAINT fk_user_stat_method_statistics FOREIGN KEY (statistics_idx) REFERENCES moneylog.tbl_user_statistics(idx) ON DELETE CASCADE;


--
-- Name: tbl_user_statistics_payment_method fk_user_stat_method_user; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_statistics_payment_method
    ADD CONSTRAINT fk_user_stat_method_user FOREIGN KEY (id_key) REFERENCES moneylog.tbl_user(id_key);


--
-- Name: tbl_user_statistics_weekly fk_user_stat_weekly_statistics; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_statistics_weekly
    ADD CONSTRAINT fk_user_stat_weekly_statistics FOREIGN KEY (statistics_idx) REFERENCES moneylog.tbl_user_statistics(idx) ON DELETE CASCADE;


--
-- Name: tbl_user_statistics_weekly fk_user_stat_weekly_user; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_statistics_weekly
    ADD CONSTRAINT fk_user_stat_weekly_user FOREIGN KEY (id_key) REFERENCES moneylog.tbl_user(id_key);


--
-- Name: tbl_user_statistics fk_user_statistics_user; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_statistics
    ADD CONSTRAINT fk_user_statistics_user FOREIGN KEY (id_key) REFERENCES moneylog.tbl_user(id_key);


--
-- Name: tbl_user_expend_target_default fk_user_target_default_expend_group; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_expend_target_default
    ADD CONSTRAINT fk_user_target_default_expend_group FOREIGN KEY (expend_group_idx) REFERENCES moneylog.tbl_user_expend_group(idx);


--
-- Name: tbl_user_expend_target_default fk_user_target_default_user; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_expend_target_default
    ADD CONSTRAINT fk_user_target_default_user FOREIGN KEY (id_key) REFERENCES moneylog.tbl_user(id_key);


--
-- Name: tbl_user_expend_target_monthly fk_user_target_monthly_expend_group; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_expend_target_monthly
    ADD CONSTRAINT fk_user_target_monthly_expend_group FOREIGN KEY (expend_group_idx) REFERENCES moneylog.tbl_user_expend_group(idx);


--
-- Name: tbl_user_expend_target_monthly fk_user_target_monthly_user; Type: FK CONSTRAINT; Schema: moneylog; Owner: -
--

ALTER TABLE ONLY moneylog.tbl_user_expend_target_monthly
    ADD CONSTRAINT fk_user_target_monthly_user FOREIGN KEY (id_key) REFERENCES moneylog.tbl_user(id_key);


--
-- PostgreSQL database dump complete
--

\unrestrict moneylogdumpkey

